### PR TITLE
tr_shader: skip standalone lightmaps, they are assumed to be buggy

### LINKED ISSUE #322: Broken lantern/candle in metro map, light emitting shader is displayed
I've noticed this issue a long time ago, but #301 seems to also trigger it in Terminus. It may be time to look at it…

Look at those candles and lanterns, how they look in Unvanquished:

[metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-172144-766.unvanquished-metro.jpg)

[metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-172202-942.unvanquished-metro.jpg)

[metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-172213-958.unvanquished-metro.jpg)

[metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-172244-926.unvanquished-metro.jpg)

And how they look in Tremulous:

[metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-192524-525.tremulous-metro.jpg)

[metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-192532-741.tremulous-metro.jpg)

[metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-192538-625.tremulous-metro.jpg)

[metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-192906-579.tremulous-metro.jpg)

Along with the flame, you'll notice those square textures in NetRadiant (those things are `misc_model` entities so they are meant to be baked in BSP):

[metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-170352-447.netradiant-metro.png)

[metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-170459-128.netradiant-metro.png)

[metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-170549-380.netradiant-metro.png)

[metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-172345-143.netradiant-metro.png)

Those squares textures are in fact… light emitting shaders, that's a clever hack to ship an md3 model with built-in lighting (with light orientation etc.). We see how those light emitting shaders are set:

[metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-194539-716.netradiant-metro.png)

[metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-194543-140.netradiant-metro.png)

[metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-200200-081.unvanquished-metro.jpg)

The one floating above or in front of the lantern is meant to use the back splash feature of the light emitting shader to lit the ground or the wall.

This is the code for the square light emitting shader:

```c
//lanterne1.md3 self lightning
models/mapobjects/kosad/lanterne/lumieresoft
{
	qer_editorimage models/mapobjects/kosad/lanterne/lumieresoft
	qer_trans .2

	q3map_surfacelight 5000
	q3map_lightrgb 1 .8 .4
	q3map_backsplash 30 4

	{
		map $lightmap
		blendfunc filter
	}
}
```

What's weird is that this lightmap is not meant to be displayed at all so I don't know why there is a lightmap stage, maybe to be sure the compiler will not ignore the shader and the light will be emitted.

The `blendFunc filter` operation is the [default operation](https://github.com/DaemonEngine/Daemon/blob/0e001477c5c05249348efc8a612310c2bec63393/src/engine/renderer/tr_shader.cpp#L4697) to blend a lightmap over a diffuseMap. What's weird is that if we don't take in account this material is not meant to be rendered, this is a lightmap blended with nothing. This is like _undefined behaviour_.

Then, if we look at the code of the candle flame shader:

```c
textures/metro/kosad_flammebougie
{
	qer_editorimage textures/metro/kosad_flammebougie1

	surfaceparm nolightmap
	surfaceparm nomarks
	surfaceparm trans

	cull disable
	deformvertexes autosprite2

	{
		animmap 50 textures/metro/kosad_flammebougie1 textures/metro/kosad_flammebougie2 textures/metro/kosad_flammebougie3 textures/metro/kosad_flammebougie4 textures/metro/kosad_flammebougie5 textures/metro/kosad_flammebougie6 textures/metro/kosad_flammebougie7 textures/metro/kosad_flammebougie8
		blendfunc add
	}
}
```

It's an animMap blended with `add` operation (like glow maps), added over… nothing.

Note that those pictures are jpeg with black bacground, the right operation may be `alphaFunc GT0` or `alphaFunc GE128`.

The blendFunc are usually used to blend multiple stage within shaders, that's not the same purpose.

This time, the material must be displayed, but not the way it is.

### PR DESCRIPTION
**Pull request by illwieckz**
Skip standalone lightmaps, they are assumed to be buggy, fixes #322:

- https://github.com/DaemonEngine/Daemon/issues/322

Extracted from:

- https://github.com/DaemonEngine/Daemon/pull/1406

### CODE REVIEW

**Review by VReaperV — APPROVED** [review]
LGTM

File: src/engine/renderer/tr_shader.cpp [hunk 1]
```diff
@@ -5171,6 +5171,14 @@ static void FinishStages()
 	bool shaderHasNoLight = true;
 	bool lightStageFound = false;
 
+	/* Skip standalone lightmaps, they are assumed to be buggy,
+	see: https://github.com/DaemonEngine/Daemon/issues/322 */
+	if ( numStages == 1 && stages[ 0 ].type == stageType_t::ST_LIGHTMAP )
+	{
+		stages[ 0 ].active = false;
```
Comment (slipher) [inline src/engine/renderer/tr_shader.cpp:5178]: This should print a warning.

Comment (illwieckz) [reply src/engine/renderer/tr_shader.cpp:5185]: Done.

**Comment by slipher** [comment]
LGTM
