### PR TITLE
Fix geometry optimiser

### LINKED ISSUE #1651: Issues with MergeDuplicateVertices hashing/equality
These issues concern the commit 7160194c "Merge duplicate map vertices" from #1640.

- `MapVertHasher` does some out-of-bounds and unaligned reads. For example `xyz` is a 12-byte `float[3]` so on 64-bit platforms, `*( ( size_t* ) &vert.xyz[2] )` reads bytes 8-16, past the end of it. (Also reading a float through a `size_t` pointer is undefined behavior, though we use `-fno-strict-aliasing` to instruct the compiler to allow it.) We have `Util::bit_cast` for stuff like converting a float to its `uint32_t` bit pattern.
- Since the hash function apparently is supposed to require `st` to be exactly equal for two verts to match, the equality function `MapVertEqual` probably should too. The hash function requires exact equality for xyz and st while the equality function requires exact equality for xyz but approximate for st.
- ArrayBytes() returns the object size so `lhs.lightColor.ArrayBytes() == rhs.lightColor.ArrayBytes()` is always true.

### PR DESCRIPTION
**Pull request by VReaperV**
Fixes #1651

I opted for making the hash not use uv's instead, as it didn't seem to have much of any effect on the loading time, but resulted in merging a few more vertices. 

Also fixed sky brushes being added as surfaces to the material system.

### CODE REVIEW

**Comment by slipher** [comment]
The commit `Don't hash the uv's in geometry optimiser` does the opposite of its description. It adds them back to the hash, while the previous commit removes them.

**Comment by VReaperV** [comment]
> The commit `Don't hash the uv's in geometry optimiser` does the opposite of its description. It adds them back to the hash, while the previous commit removes them.

Fixed.

**Comment by slipher** [comment]
The station15 sun disappears when material system is enabled.

unvanquished-station15-autosprite1-sun

(There should be a sun)

**Comment by slipher** [comment]
illwieckz has said the station15 sun uses something called a "skybox portal". (You can see 2 copies of it if noclipping.) I have no idea where this implemented in the code. There is a flag called RF_SKYBOXPORTAL but it's never set anywhere, so apparently unrelated.

**Comment by VReaperV** [comment]
> The station15 sun disappears when material system is enabled.
> 
> unvanquished-station15-autosprite1-sun
> 
> (There should be a sun)

Fixed.

File: src/engine/renderer/Material.cpp [hunk 1]
```diff
@@ -1847,10 +1855,10 @@ void MaterialSystem::AddPortalSurfaces() {
 void MaterialSystem::AddAutospriteSurfaces() {
 	tr.currentEntity = &tr.worldEntity;
 
-	for ( const bspSurface_t* surface : autospriteSurfaces )
+	for ( const MaterialSurface& surface : autospriteSurfaces )
 	{
-		R_AddDrawSurf( surface->data, surface->shader,
-		               surface->lightmapNum, surface->fogIndex, true );
+		R_AddDrawSurf( surface.surface, surface.shader,
```
Comment (slipher) [inline src/engine/renderer/Material.cpp:1860]: Why does the type of `autospriteSurfaces` need to be changed? Seems to be using the same information that was already there before.

Comment (VReaperV) [reply src/engine/renderer/Material.cpp:1860]: Ah, yea, I did that in the process of trying to find the issue with station15 sun. I guess it can be changed back to `bspSurface_t*`.

Comment (VReaperV) [reply src/engine/renderer/Material.cpp:1860]: Back to `bspSurface_t*`.

**Comment by slipher** [comment]
LGTM
