### PR TITLE
Make fog into a stage, fix some issues with it

### LINKED ISSUE #537: SSAO displayed above fog from behind wall
On this screenshot (hangar28 map), there is a fog between the player's eyes and the wall, though, the SSAO dark corner is visible.

[ssao above fog from behind wall](https://dl.illwieckz.net/b/daemon/bugs/ssao-above-fog-from-behind-wall/unvanquished_2021-10-13_020303_000.jpg)

I noticed SSAO is not done on skybox textures, so maybe we can exclude such surface as well.

For a start, we must check if SSAO is drawn on surfaces with `nolightmap`, I guess it must not.

### PR DESCRIPTION
**Pull request by VReaperV**
Changes fog from being done based on an if statement in `Tess_StageIteratorColor()` to being added as a surface with one of two new defaut fog shaders - similar to how we add depth pre-pass surfaces. The 2 new default shaders are for fogs with FP_EQUAL and FP_LE fog passes.

- Adds fog to material system. Fog surfaces are added as stages to the main surface, like it's already done with depth pre-pass surfaces.
- Slightly reworked how depth and fog surfaces are linked to the main surface, now `R_AddDrawSurf()` returns the index of the surface, to get the correct one.
- Moved some early-return fog checks to shader parsing/`R_AddDrawSurf()`.
- Added `u_FogMap` since all fogs use the same image, so it can be made global, and cleaned up `Render_fog()` and fog processing a bit.
- Fixes #537 by rendering all fog surfaces with `SS_FOG`, which is done after SSAO.
- Fixed incorrect max stage count for material system.

### CODE REVIEW

**Comment by slipher** [comment]
What are some maps with fog to try it out? The only one I know off the top of my head is atcshd.

**Comment by VReaperV** [comment]
The other 2 I know of are https://users.unvanquished.net/~sweet/pkg/map-assault_0%2Bv7.1-beta4.dpk and https://users.unvanquished.net/~sweet/pkg/map-hangar28_1.dpk.

File: src/engine/renderer/tr_local.h [hunk 1]
```diff
@@ -3093,7 +3099,7 @@ inline bool checkGLErrors()
 
 	void           R_AddPolygonSurfaces();
 
-	void           R_AddDrawSurf( surfaceType_t *surface, shader_t *shader, int lightmapNum, int fogNum, bool bspSurface = false );
+	int           R_AddDrawSurf( surfaceType_t *surface, shader_t *shader, int lightmapNum, int fogNum, bool bspSurface = false );
```
Comment (illwieckz) [inline src/engine/renderer/tr_local.h:3102]: Same (and in fact alignment is already lost, so better strip that space).

**Review by illwieckz — APPROVED** [review]
LGTM! And it works well on my end!

File: src/engine/renderer/tr_shader.cpp [hunk 2]
```diff
@@ -7155,11 +7177,41 @@ static void CreateInternalShaders()
...
 	stages[ 0 ].bundle[ 0 ].image[ 0 ] = tr.defaultImage;
 	stages[ 0 ].active = true;
 	stages[ 0 ].stateBits = GLS_DEFAULT;
 	tr.defaultShader = FinishShader();
+
+	Q_strncpyz( shader.name, "<fogEqual>", sizeof( shader.name ) );
+
+	shader.type = shaderType_t::SHADER_3D_DYNAMIC;
+	shader.sort = Util::ordinal( shaderSort_t::SS_FOG );
+	shader.noFog = true;
```
Comment (slipher) [inline src/engine/renderer/tr_shader.cpp:7192]: I don't see why we should specially disable fog for the not-found shader.

File: src/engine/renderer/tr_shade.cpp [hunk 3]
```diff
@@ -2325,52 +2325,43 @@ void Render_liquid( shaderStage_t *pStage )
...
-	{
+	if ( materialSystem.generatingWorldCommandBuffer ) {
+		Tess_DrawElements();
 		return;
 	}
 
-	// ydnar: no world, no fogging
-	if ( backEnd.refdef.rdflags & RDF_NOWORLDMODEL )
+	// no fog pass in snooper
+	// WTF is a snooper?
```
Comment (slipher) [inline src/engine/renderer/tr_shade.cpp:2336]: This I guess: https://wolfenstein.fandom.com/wiki/Snooper_rifle

File: src/engine/renderer/tr_shader.cpp [hunk 4]
```diff
@@ -5971,6 +5963,14 @@ static shader_t *FinishShader()
 		}
 	}
 
+	if ( shader.sort <= Util::ordinal( shaderSort_t::SS_OPAQUE ) ) {
+		shader.fogPass = fogPass_t::FP_EQUAL;
+	} else if ( shader.contentFlags & CONTENTS_FOG ) {
+		shader.fogPass = fogPass_t::FP_LE;
+	}
+
+	shader.noFog = shader.noFog || shader.fogPass == fogPass_t::FP_NONE || ( backEnd.refdef.rdflags & RDF_NOWORLDMODEL );
```
Comment (slipher) [inline src/engine/renderer/tr_shader.cpp:5980]: rdflags can change each frame so you can't use it here.

File: src/engine/renderer/tr_shade.cpp [hunk 5]
```diff
@@ -2352,19 +2347,20 @@ static void Render_fog()
...
 	fogDistanceVector[ 1 ] = -backEnd.orientation.modelViewMatrix[ 6 ];
 	fogDistanceVector[ 2 ] = -backEnd.orientation.modelViewMatrix[ 10 ];
 	fogDistanceVector[ 3 ] = DotProduct( local, backEnd.viewParms.orientation.axis[ 0 ] );
 
 	// scale the fog vectors based on the fog's thickness
-	fogDistanceVector[ 0 ] *= fog->tcScale;
-	fogDistanceVector[ 1 ] *= fog->tcScale;
-	fogDistanceVector[ 2 ] *= fog->tcScale;
-	fogDistanceVector[ 3 ] *= fog->tcScale;
+	VectorScale( fogDistanceVector, fog->tcScale, fogDistanceVector );
```
[the remark this answers is not in the document]
Comment (slipher) [reply src/engine/renderer/tr_shade.cpp:2359]: Apparently it was fixed in a subsequent commit

File: src/engine/renderer/glsl_source/fogQuake3_fp.glsl [hunk 6]
```diff
@@ -24,7 +24,7 @@ Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 
 #define FOGQUAKE3_GLSL
 
-uniform sampler2D	u_ColorMap;
+uniform sampler2D	u_FogMap;
```
[the remark this answers is not in the document]
Comment (slipher) [reply src/engine/renderer/glsl_source/fogQuake3_fp.glsl:27]: What do you mean?

[the remark this answers is not in the document]
Comment (illwieckz) [reply src/engine/renderer/glsl_source/fogQuake3_fp.glsl:27]: The `uniform sampler2D u_FogMap;`, actually that's a tab and not many spaces, but fixing the ugliness of the code when modifying is the best way to prevent noisy restyling commits. Nothing is blocking there, just noticing the code can be beautified at the same time and that would save us a noisy restyle commit.

File: src/engine/renderer/tr_shader.cpp (hunk 4 above)
Comment (VReaperV) [reply src/engine/renderer/tr_shader.cpp:5980]: Hmm, I thought it's only used in menus and such, but apparently it's only used for hyperspace.

File: src/engine/renderer/tr_shade.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (VReaperV) [reply src/engine/renderer/tr_shade.cpp:2359]: Yeah, I didn't realize I put the initial changed into the previous commit at the time.

File: src/engine/renderer/tr_shader.cpp (hunk 4 above)
Comment (VReaperV) [reply src/engine/renderer/tr_shader.cpp:5980]: In fact, given that it's not used for anything else and hyperspace already has its own flag, I think `RDF_NOWORLDMODEL` can just be NUKED. Out of scope for this pr though.

File: src/engine/renderer/tr_shade.cpp (hunk 3 above)
Comment (VReaperV) [reply src/engine/renderer/tr_shade.cpp:2336]: Perhaps. Apparently Wolf:ET had a check for `tr.refdef.rdflags & RDF_SNOOPERVIEW` at https://github.com/id-Software/Enemy-Territory/blob/40342a9e3690cb5b627a433d4d5cbf30e3c57698/src/renderer/tr_shade.c#L803.

File: src/engine/renderer/tr_shader.cpp (hunk 4 above)
Comment (VReaperV) [reply src/engine/renderer/tr_shader.cpp]: Anyway, fixed the initial issue.

File: src/engine/renderer/tr_shade.cpp (hunk 3 above)
Comment (VReaperV) [reply src/engine/renderer/tr_shade.cpp]: I've removed that comment now because it doesn't apply to daemon.

File: src/engine/renderer/glsl_source/fogQuake3_fp.glsl (hunk 6 above)
[the remark this answers is not in the document]
Comment (VReaperV) [reply src/engine/renderer/glsl_source/fogQuake3_fp.glsl]: Alright, done.

File: src/engine/renderer/tr_local.h (hunk 1 above)
Comment (VReaperV) [reply src/engine/renderer/tr_local.h]: Also done now.

File: src/engine/renderer/tr_shader.cpp (hunk 2 above)
Comment (VReaperV) [reply src/engine/renderer/tr_shader.cpp:7192]: I suppose that line can be dropped.

Comment (VReaperV) [reply src/engine/renderer/tr_shader.cpp]: I tried it, it seems to work fine, so I added that change.
