### PR TITLE
Abort on missing required GL extension, fix #348

### LINKED ISSUE #348: segfault on glBindFramebuffer( GL_FRAMEBUFFER, 0 )
I attempted to run Unvanquished on two Nvidia OpenGL 2.1 GPUs:

- GeForce N6600LE, workstation discrete card (PCIe x16) GPU (~2004)
- GeForce 6150LE, workstation onboard (HyperTransport) GPU (~2006)

I don't expect Unvanquished to perform properly on them (even gnome-shell is garbage), but the crash I experienced is interesting.

Basically, at some point there is awarning about the game not being able to create a GL context:

```
Warn: SDL_GL_CreateContext failed: Could not create GL context: GLXBadFBConfig
```
and later a segfault occurs:

```
Thread 1 "daemon" received signal SIGSEGV, Segmentation fault.
```

GDB saids:

```
#1  0x00005555558311c3 in GL_SetDefaultState () at …/Daemon/src/engine/renderer/tr_init.cpp:871
```

This segfault occurs on this line:

```c++
		glBindFramebuffer( GL_FRAMEBUFFER, 0 );
```

See: https://github.com/DaemonEngine/Daemon/blob/6b94e2e890f893afdc55b7f70bd58cb39f3cafcd/src/engine/renderer/tr_init.cpp#L871

Can it be possible the segfault is related to this warning?

Even if I don't expect Unvanquished to be playable on such hardware, we may expect the engine to not segfault when the system does not provide the necessary requirement, and handle the issue gracefully.

Some recent hardware but with incomplete or work-in-progress driver may reproduce the segfault.

If the warning and the segfault are related, the warning must be an error and the use must get some explanations about what's going on.

----

For reference, extensive log for the GeForce N6600LE (NV43):

```
Reading symbols from …/build/engine/debug/daemon...
(gdb) r
Starting program: …/build/engine/debug/daemon -set logs.suppression.enabled 0 -set logs.logLevel.default debug -set logs.logLevel.audio debug -set language en -set developer 1 -set vm.cgame.type 3 -set vm.sgame.type 3 -libpath …/build/vms/debug -pakpath …/build/assets/test -pakpath ~/.local/share/unvanquished/base/pkg

[…]

--- Common Initialization Complete ---
Calling GetRefAPI…
^5Debug: GetRefAPI()
^5Debug: ----- R_Init -----
SDL_Init( SDL_INIT_VIDEO )... 
Using SDL Version 2.0.10

[…]

SDL using driver "x11"
Initializing OpenGL display
Display aspect: 1.778
...setting mode -1:
 1280 720
^3Warn: SDL_GL_CreateContext failed: Could not create GL context: GLXBadFBConfig

Using 24 Color bits, 24 depth, 8 stencil display.
Using GLEW 2.1.0
Using enhanced (GL3) Renderer in GL 2.x mode...
Available modes: '1920x1080 1280x800 1440x900 1680x1050 640x480 800x600 1024x768 1280x960 1280x1024 '
GL_RENDERER: NV43
Detected graphics driver class 'Mesa'
Detected graphics hardware class 'generic'
Initializing OpenGL extensions
...ignoring GL_ARB_debug_output
...found shading language version 120
...using GL_ARB_half_float_pixel
...GL_ARB_texture_float not found
...GL_EXT_gpu_shader4 not found
...GL_EXT_texture_integer not found
...GL_ARB_texture_rg not found
...GL_ARB_texture_gather not found
...using GL_EXT_texture_filter_anisotropic
...using GL_ARB_half_float_vertex
...GL_ARB_framebuffer_object not found
...using GL_ARB_get_program_binary
...using GL_ARB_buffer_storage
...GL_ARB_uniform_buffer_object not found
...using GL_ARB_map_buffer_range
...using GL_ARB_sync
^5Debug: ------- Input Initialization -------
^5Debug: Joystick is not active.
^5Debug: Gamepad is not active.
^5Debug: ------------------------------------
^3Warn: SSAO not used because GL_ARB_texture_gather is not available.
glsl shaders took 179 msec to build

Thread 1 "daemon" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) thread apply all bt

[…]

Thread 1 (Thread 0x7ffff4f5cc00 (LWP 13482)):
#0  0x0000000000000000 in ?? ()
#1  0x00005555558311c3 in GL_SetDefaultState () at …/Daemon/src/engine/renderer/tr_init.cpp:871
#2  0x000055555582fe6f in InitOpenGL () at …/Daemon/src/engine/renderer/tr_init.cpp:360
#3  0x0000555555833c8d in R_Init () at …/Daemon/src/engine/renderer/tr_init.cpp:1382
#4  0x000055555584c224 in RE_BeginRegistration (glconfigOut=0x555555ffe1a0 <cls+3012928>, glconfig2Out=0x555555fffddc <cls+3020156>) at …/Daemon/src/engine/renderer/tr_model.cpp:276
#5  0x0000555555743626 in CL_InitRenderer () at …/Daemon/src/engine/client/cl_main.cpp:2597
#6  0x00005555557438e8 in CL_StartHunkUsers () at …/Daemon/src/engine/client/cl_main.cpp:2671
#7  0x000055555575a535 in Application::ClientApplication::Initialize (this=0x5555560256e0 <Application::GetApp()::app>, uri=...) at …/Daemon/src/engine/client/ClientApplication.cpp:76
#8  0x00005555558fbd8d in Application::Initialize (uri=...) at …/Daemon/src/engine/framework/Application.cpp:69
#9  0x0000555555939fa8 in Sys::Init (argc=30, argv=0x7fffffffdce8) at …/Daemon/src/engine/framework/System.cpp:659
#10 0x000055555593a1f4 in main (argc=30, argv=0x7fffffffdce8) at …/Daemon/src/engine/framework/System.cpp:674
(gdb) 
```

and for the GeForce 6150LE (NV4E):

```
Reading symbols from …/build/engine/debug/daemon...
(gdb) r
Starting program: …/build/engine/debug/daemon -set logs.suppression.enabled 0 -set logs.logLevel.default debug -set logs.logLevel.audio debug -set language en -set developer 1 -set vm.cgame.type 3 -set vm.sgame.type 3 -libpath …/build/vms/debug -pakpath …/build/assets/test -pakpath ~/.local/share/unvanquished/base/pkg

[…]

--- Common Initialization Complete ---
Calling GetRefAPI…
^5Debug: GetRefAPI()
^5Debug: ----- R_Init -----
SDL_Init( SDL_INIT_VIDEO )... 
Using SDL Version 2.0.10

[…]

SDL using driver "x11"
Initializing OpenGL displayThread 1 "daemon" received signal SIGSEGV, Segmentation fault.
Display aspect: 1.250
...setting mode -1:
 1280 720
^3Warn: SDL_GL_CreateContext failed: Could not create GL context: GLXBadFBConfig

Using 24 Color bits, 24 depth, 8 stencil display.
Using GLEW 2.1.0
Using enhanced (GL3) Renderer in GL 2.x mode...
Available modes: '1280x1024 640x480 800x600 1024x768 '
GL_RENDERER: NV4E
Detected graphics driver class 'Mesa'
Detected graphics hardware class 'generic'
Initializing OpenGL extensions
...ignoring GL_ARB_debug_output
...found shading language version 120
...using GL_ARB_half_float_pixel
...GL_ARB_texture_float not found
...GL_EXT_gpu_shader4 not found
...GL_EXT_texture_integer not found
...GL_ARB_texture_rg not found
...GL_ARB_texture_gather not found
...using GL_EXT_texture_filter_anisotropic
...using GL_ARB_half_float_vertex
...GL_ARB_framebuffer_object not found
...using GL_ARB_get_program_binary
...using GL_ARB_buffer_storage
...GL_ARB_uniform_buffer_object not found
...using GL_ARB_map_buffer_range
...using GL_ARB_sync
^5Debug: ------- Input Initialization -------
^5Debug: Joystick is not active.
^5Debug: Gamepad is not active.
^5Debug: ------------------------------------
^3Warn: SSAO not used because GL_ARB_texture_gather is not available.
glsl shaders took 1103 msec to build

Thread 1 "daemon" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) thread apply all bt

[…]

Thread 1 (Thread 0x7ffff4f5cc00 (LWP 32621)):
#0  0x0000000000000000 in ?? ()
#1  0x00005555558311c3 in GL_SetDefaultState () at …/Daemon/src/engine/renderer/tr_init.cpp:871
#2  0x000055555582fe6f in InitOpenGL () at …/Daemon/src/engine/renderer/tr_init.cpp:360
#3  0x0000555555833c8d in R_Init () at …/Daemon/src/engine/renderer/tr_init.cpp:1382
#4  0x000055555584c224 in RE_BeginRegistration (glconfigOut=0x555555ffe1a0 <cls+3012928>, glconfig2Out=0x555555fffddc <cls+3020156>) at …/Daemon/src/engine/renderer/tr_model.cpp:276
#5  0x0000555555743626 in CL_InitRenderer () at …/Daemon/src/engine/client/cl_main.cpp:2597
#6  0x00005555557438e8 in CL_StartHunkUsers () at …/Daemon/src/engine/client/cl_main.cpp:2671
#7  0x000055555575a535 in Application::ClientApplication::Initialize (this=0x5555560256e0 <Application::GetApp()::app>, uri=...) at …/Daemon/src/engine/client/ClientApplication.cpp:76
#8  0x00005555558fbd8d in Application::Initialize (uri=...) at …/Daemon/src/engine/framework/Application.cpp:69
#9  0x0000555555939fa8 in Sys::Init (argc=30, argv=0x7fffffffdd08) at …/Daemon/src/engine/framework/System.cpp:659
#10 0x000055555593a1f4 in main (argc=30, argv=0x7fffffffdd08) at …/Daemon/src/engine/framework/System.cpp:674
(gdb) 
```

### PR DESCRIPTION
**Pull request by illwieckz**
Abort on missing required GL extension, fix #348

I would appreciate comments on error message wording.

### CODE REVIEW

File: src/engine/sys/sdl_glimp.cpp [hunk 1]
```diff
@@ -966,7 +966,8 @@ static void RequireExt( bool hasExt, const char* name )
 	}
 	else
 	{
-		logger.WithoutSuppression().Notice("...GL_%s not found", name );
+		SDL_DestroyWindow( window );
```
Comment (slipher) [inline src/engine/sys/sdl_glimp.cpp:969]: This will be done already by `Sys::Error -> Sys::Shutdown -> Application::Shutdown -> ClientApplication::Shutdown -> CL_Shutdown -> CL_ShutdownRef -> re.Shutdown = RE_Shutdown -> GLimp_Shutdown -> SDL_DestroyWindow`

Looks good otherwise.

Comment (illwieckz) [reply src/engine/sys/sdl_glimp.cpp:969]: Yeah, I was wondering about the fact the window is destroyed after the error message is displayed, leaving undefined content on screen until the user acknowledges the error.

Comment (illwieckz) [reply src/engine/sys/sdl_glimp.cpp:969]: We may modify `Sys::Error` to destroy the window before printing the error message in another PR instead.

**Comment by illwieckz** [comment]
travis failure is a travis issue
