### PR TITLE
Reimport a mismerged fix

### LINKED ISSUE #1297: Negative portal scissor size on 0.55 branch
On `for-0.55.0/sync` I periodically get errors about negative size from SetViewportAndScissor on map `test-portals`. This can be seen with r_checkGLErrors or the other GL debug callback thing, for example:
```
^3Warn: DEBUG_TYPE_ERROR: severity: high msg: GL_INVALID_VALUE error generated. Width and height must not be negative.
```

Some code to prevent negative values was removed on the branch by 948a3fea80d8105cbbacbc8e6d147912c277b179.

### PR DESCRIPTION
**Pull request by illwieckz**
It looks like merge commit 2ea20a9f29ac4f0b886d001accadc8eadad19a47 was wrong and left this change aside.

Hopefully fixes #1297:

- https://github.com/DaemonEngine/Daemon/issues/1297

----

Fix portal scissor test

Width and height in glScissor() must not be negative, so if surfRect has lower x2 or y2 than x1 or y1, then flip the scissor parameters.

### CODE REVIEW

File: src/engine/renderer/tr_main.cpp [hunk 1]
```diff
@@ -1841,6 +1841,17 @@ bool R_MirrorViewBySurface(drawSurf_t *drawSurf)
 	newParms.scissorWidth = surfRect.coords[2] - surfRect.coords[0] + 1;
 	newParms.scissorHeight = surfRect.coords[3] - surfRect.coords[1] + 1;
 
+
```
Comment (VReaperV) [inline src/engine/renderer/tr_main.cpp:1844]: Extraneous newline.

**Review by VReaperV — APPROVED** [review]
LGTM.

**Comment by illwieckz** [comment]
Almost a day has passed, and anyway this was already approved long time ago, it was just left over by mistake, let's merge it.
